In [27]:
import numpy
import pandas

In [28]:
data = pandas.read_csv("diabetes.csv")
df = pandas.DataFrame(data)
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [29]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [30]:
# target >>> outcome
# input features >>> Pregnancies	Glucose	BloodPressure	SkinThickness	Insulin	BMI	DiabetesPedigreeFunction	Age

# No missing values so no need of filling

# scikit-learn >>> Contains tools to build, train, test and evaluating ML models easily
# ==========================================================================================================

In [31]:
# Splitting
#=========================
X = df.iloc[:,:-1]

Y = df.iloc[:,-1]
Y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

Input Features >>> 70 % training  30 % testing >>> X_train  X_test
Target >>>         70 % training  30 % evaluation >>> Y_train  Y_test

In [32]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)

X_train


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
204            6      103             72             32      190  37.7   
31             3      158             76             36      245  31.6   
633            1      128             82             17      183  27.5   
377            1       87             60             37       75  37.2   
382            1      109             60              8      182  25.4   
..           ...      ...            ...            ...      ...   ...   
6              3       78             50             32       88  31.0   
434            1       90             68              8        0  24.5   
631            0      102             78             40       90  34.5   
362            5      103            108             37        0  39.2   
535            4      132              0              0        0  32.9   

     DiabetesPedigreeFunction  Age  
204                     0.324   55  
31                      0.851   28  
633                     0.115   22  
377                     0.509   22  
382                     0.947   21  
..                        ...  ...  
6                       0.248   26  
434                     1.138   36  
631                     0.238   24  
362                     0.305   65  
535                     0.302   23  

[537 rows x 8 columns]

In [33]:
# Z = (x - mean) / standardDeviation    >>>   Standard Scaler

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_train

"""
No need to give X_test to fit method
"""
X_test = scaler.transform(X_test)
X_test


array([[-1.131388  , -0.52581163, -0.05806965, ..., -1.46994212,
        -0.70245691, -0.95474747],
       [ 1.52298006, -1.02512346, -0.36229799, ..., -1.16037503,
        -0.98135339, -0.0474609 ],
       [ 0.63819071, -0.46339765,  0.9560248 , ...,  0.61034869,
         0.75433216, -0.2124221 ],
       ...,
       [-0.24659865,  0.87850291,  0.34756813, ..., -1.34611529,
        -0.78849944,  0.28246149],
       [-0.54152843,  0.0047072 , -0.86934522, ...,  0.53605259,
         1.01839372, -0.45986389],
       [-0.83645821,  0.78488194,  1.26025314, ...,  2.15818411,
        -0.34048488, -0.54234449]], shape=(231, 8))

In [34]:
"""
KNN algorithm 
"""
# Training
from sklearn.neighbors import KNeighborsClassifier  # class method KNN
knn = KNeighborsClassifier()
knn = knn.fit(X_train,Y_train)


In [35]:
# Testing
y_pred = knn.predict(X_test)    # Model will predict the result for untrained data
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0])

PERFORMANCE EVALUATION

In [36]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_pred,Y_test))


0.7532467532467533


In [37]:
# Acccuracy Score = correct predictions / total no. of predictions
# Recall
# Precision
# f1-score
# Confusion matrix (Only for classification)

In [38]:
# Confusion matrix
# TruePositive, TrueNegative, FalsePositive, FalseNegative

# real result      model result
#     1                 1       #True Positive
#     1                 0       #False Negative
#     0                 1       #False Positive
#     0                 0       #True Negative


In [39]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test,y_pred)
cm

array([[134,  17],
       [ 40,  40]])