create an array of numbers from 1 to 10

In [ ]:
import numpy

In [4]:
numbers = list(range(1, 11))

In [ ]:
result = numpy.array(numbers)
print(result)

[ 1  2  3  4  5  6  7  8  9 10]


Types of Array
=========================

one-dimensional >>>>> x      list = [1,2,3,4,5]

two-dimensional >>>>> x,y    dataset list = [[1,2,3,4],[5,6,7,8]]

three-dimensional >>>>> x,y,z    list = [[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]

In [8]:
numbers = [[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]
n = numpy.array(numbers)
print(n)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


Create a 2D array

In [16]:
numbers = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
result = numpy.array(numbers)
result


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
result[2,2] # 11
result[-1]  # [9,10,11,12]
result[-1,1] # 10
result[:,2] # [3,7,11]
result[0:2,2::] # [[3,4],[7,8]]
result[1::,1:3] # [[6,7],[10,11]]
# select last 2 rows and first 2 columns
result[1::] #[[ 5,  6,  7,  8],[ 9, 10, 11, 12]]
result[:,0:2] # [[1,2],[5,6],[9,10]]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [38]:
result.mean() # 6.5
result.min()  # 1
result.max()  # 12
result.sum()  # 78
result.shape # (3,4)
result.dtype # dtype('int32')

dtype('int64')

In [39]:
result[-1].sum() # To get sum of elements in last row

np.int64(42)

Create a 4x4 matrix

print first row
print last column
print first 2 rows and first 3 columns using slicing
find a specific element using index values
find sum of all elements
find min and max of the array
find max of 3rd row
find sum of elements in last row
find sum of elements in last column

In [49]:
numbers = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
result = numpy.array(numbers)
result


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
result[0]
result[:,-1]
result[0:2]
result[:,:3]
result[1,2]
result.sum()
result.min()
result.max()
result[2].max()
result[:,-1].sum()
result[-1].sum()

array([ 4,  8, 12, 16])

In [62]:
numbers = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
result = numpy.array(numbers)
result

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [67]:
result[result > 10] # filter all elements greater than 10
result[result % 2 == 0] # filter all even numbers
result[result % 3 == 0] # filter all odd numbers
result[result % 2 == 0].sum() # sum of all even numbers
result[result % 2 != 0].sum() # sum of all odd numbers

np.int64(64)

create a 4x4 array  list = [[1,2,3,4],[5,6,7,8],[3,2,1,4],[3,4,5,6]]

select first two rows

filter odd numbers from array

In [ ]:
numbers = [[1,2,3,4],[5,6,7,8],[3,2,1,4],[3,4,5,6]]

n = numpy.array(numbers)

# select first two rows
n[0:2]
"""
n[n % 2 != 0]
"""

# filter odd numbers from the first row

n[0][n[0] % 2 != 0]

In [ ]:
# find the sum of numbers greater than 5

n[n > 5].sum() # 27
numpy.sum(n[n>5]) # 27

In [ ]:
# find the numbers greater than 5 and should be odd

n[(n > 5) & (n % 2 != 0)]   # [7]

# find the sum of numbers divisible by 2 and less than 10

n[(n % 2 == 0) & (n < 10)].sum()

# find the numbers either divisible by 3 or by 5

n[(n % 3 == 0) | (n % 5 == 0)]

In [ ]:
# display sum of all rows

numpy.sum(n,axis=1)

# display sum of all columns

numpy.sum(n,axis=0)

type of matrices
===================================
zero matrix, one

In [ ]:
numpy.zeros((2,3),dtype=int)
# array with all elements as zero
# syntax : numpy.zeros((row_value,column_value))
numpy.ones((3,4),dtype=int)
# array with all elements as one
# syntax : numpy.ones((row_value,column_value))
numpy.identity(3)
# syntax : numpy.identity(n)  n represents row and column value
#all the diagonal elements are 1 and all other elements are 0
# only possible in square matrix

In [ ]:
# create a 3 x 4 matrix

n = numpy.random.randint(1,50,size=(3,4))


In [ ]:
# Replace a specific element

n[0,2] = 10     # only one element changes to 10
n[0] = 10       # the values of an entire row changes to 10
n

Create am array of 4 x 4 of values 10 to 25
display the array
find row sum and column sum
display elements greater than 18 and less than 23
replace all elements greater than 20 with 0
find all elements that are odd or divisible by 5
Calculate the sum of last two rows
extract 2nd and 3rd column
add all the elements in array with mean of the array

In [ ]:
# Create an array of 4 x 4 of values 10 to 25
numbers = [[10,11,12,13],[14,15,16,17],[18,19,20,21],[22,23,24,25]]

n = numpy.array(numbers)

# display the array
print(n)

# find row sum and column sum
numpy.sum(n,axis=1) # row sum

numpy.sum(n,axis=0) # column sum

# display elements greater than 18 and less than 23
n[(n > 18) & (n < 25)]

# replace all elements greater than 20 with 0
n[(n > 20)] = 0

# find all elements that are odd or divisible by 5
n[(n % 2 != 0) | (n % 5 == 0)]

# Calculate the sum of last two rows
n[2:].sum()

# extract 2nd and 3rd column
n[1:3]

# add all the elements in array with mean of the array
mean1 = n.mean()
n+mean1
n
