In [1]:
import numpy
import pandas

In [2]:
data = pandas.read_csv("Lifestyle_and_Health_Risk_Prediction_Synthetic_Dataset.csv")
df = pandas.DataFrame(data)
df

age  weight  height exercise  sleep sugar_intake smoking alcohol  \
0      56      67     195      low    6.1       medium     yes     yes   
1      69      76     170     high    6.9         high      no      no   
2      46     106     153     high    6.6          low     yes      no   
3      32      54     186   medium    8.5       medium      no      no   
4      60      98     195     high    8.0          low      no      no   
...   ...     ...     ...      ...    ...          ...     ...     ...   
4995   42      75     187   medium    7.2          low      no      no   
4996   39      86     183      low    7.4          low      no      no   
4997   48      56     194     none    7.2         high     yes     yes   
4998   34     109     148   medium    9.9       medium      no      no   
4999   72      47     149     high    6.3       medium      no      no   

     married     profession   bmi health_risk  
0        yes  office_worker  17.6        high  
1         no        teacher  26.3        high  
2         no         artist  45.3        high  
3         no         artist  15.6         low  
4        yes        teacher  25.8        high  
...      ...            ...   ...         ...  
4995     yes         driver  21.4         low  
4996     yes       engineer  25.7        high  
4997     yes       engineer  14.9        high  
4998     yes         doctor  49.8         low  
4999     yes         driver  21.2         low  

[5000 rows x 12 columns]

In [3]:
df.isna().sum()

age             0
weight          0
height          0
exercise        0
sleep           0
sugar_intake    0
smoking         0
alcohol         0
married         0
profession      0
bmi             0
health_risk     0
dtype: int64

In [4]:
df['exercise'] = df['exercise'].replace({'none' : 0, 'low' : 1, 'medium' : 2, 'high' : 3})

C:\Users\Anand Vinodkumar\AppData\Local\Temp\ipykernel_4276\932263637.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['exercise'] = df['exercise'].replace({'none' : 0, 'low' : 1, 'medium' : 2, 'high' : 3})


In [5]:
df['sugar_intake'] = df['sugar_intake'].replace({'low': 0,'medium':1,'high':2})

C:\Users\Anand Vinodkumar\AppData\Local\Temp\ipykernel_4276\3693278999.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sugar_intake'] = df['sugar_intake'].replace({'low': 0,'medium':1,'high':2})


In [6]:
df['smoking'] = df['smoking'].replace({'yes' : 1, 'no' : 0})

C:\Users\Anand Vinodkumar\AppData\Local\Temp\ipykernel_4276\1651498206.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['smoking'] = df['smoking'].replace({'yes' : 1, 'no' : 0})


In [7]:
df['alcohol'] = df['alcohol'].replace({'yes' : 1, 'no' : 0})

C:\Users\Anand Vinodkumar\AppData\Local\Temp\ipykernel_4276\1358409561.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['alcohol'] = df['alcohol'].replace({'yes' : 1, 'no' : 0})


In [8]:
df['married'] = df['married'].replace({'yes' : 1, 'no' : 0})

C:\Users\Anand Vinodkumar\AppData\Local\Temp\ipykernel_4276\3789683110.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['married'] = df['married'].replace({'yes' : 1, 'no' : 0})


In [9]:
# df['profession'].unique()    >>>  To find what all values are there in the column
df['profession'] = df['profession'].replace({'office_worker' : 0, 'teacher' : 1, 'artist' : 2, 'farmer' : 3, 'driver' : 4, 'engineer' : 5, 'student' : 6, 'doctor' : 7})

C:\Users\Anand Vinodkumar\AppData\Local\Temp\ipykernel_4276\2984786361.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['profession'] = df['profession'].replace({'office_worker' : 0, 'teacher' : 1, 'artist' : 2, 'farmer' : 3, 'driver' : 4, 'engineer' : 5, 'student' : 6, 'doctor' : 7})


In [10]:
df['health_risk'] = df['health_risk'].replace({'low' : 0, 'high' : 1})

C:\Users\Anand Vinodkumar\AppData\Local\Temp\ipykernel_4276\1378753080.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['health_risk'] = df['health_risk'].replace({'low' : 0, 'high' : 1})


In [11]:
df

age  weight  height  exercise  sleep  sugar_intake  smoking  alcohol  \
0      56      67     195         1    6.1             1        1        1   
1      69      76     170         3    6.9             2        0        0   
2      46     106     153         3    6.6             0        1        0   
3      32      54     186         2    8.5             1        0        0   
4      60      98     195         3    8.0             0        0        0   
...   ...     ...     ...       ...    ...           ...      ...      ...   
4995   42      75     187         2    7.2             0        0        0   
4996   39      86     183         1    7.4             0        0        0   
4997   48      56     194         0    7.2             2        1        1   
4998   34     109     148         2    9.9             1        0        0   
4999   72      47     149         3    6.3             1        0        0   

      married  profession   bmi  health_risk  
0           1           0  17.6            1  
1           0           1  26.3            1  
2           0           2  45.3            1  
3           0           2  15.6            0  
4           1           1  25.8            1  
...       ...         ...   ...          ...  
4995        1           4  21.4            0  
4996        1           5  25.7            1  
4997        1           5  14.9            1  
4998        1           7  49.8            0  
4999        1           4  21.2            0  

[5000 rows x 12 columns]

In [12]:
# input features >>> age	weight	height	exercise	sleep	sugar_intake	smoking	alcohol	married	profession	bmi
# output    >>>    health_risk

In [13]:
X = df.iloc[:,:-1]
X
Y = df.iloc[:,-1]
Y

0       1
1       1
2       1
3       0
4       1
       ..
4995    0
4996    1
4997    1
4998    0
4999    0
Name: health_risk, Length: 5000, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)

X_train
X_test
Y_train
Y_test

1363    0
4127    1
666     0
4097    1
1376    1
       ..
751     1
2533    1
796     1
3719    1
327     0
Name: health_risk, Length: 1500, dtype: int64

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train)

X_train = scaler.transform(X_train)

X_train

X_test = scaler.transform(X_test)
X_test

array([[ 0.46022193,  0.09179763,  1.19546052, ...,  0.80247386,
         0.65940322, -0.61914888],
       [ 0.34818348, -1.04008058,  1.00617416, ...,  0.80247386,
        -0.66116398, -1.26316982],
       [-0.04395108, -0.77058577,  0.05974238, ...,  0.80247386,
        -0.22097491, -0.70420825],
       ...,
       [-0.88423944,  0.25349452, -0.94978486, ..., -1.2461465 ,
        -1.10135304,  0.79040637],
       [-0.43608565,  1.60096858, -1.58073938, ...,  0.80247386,
         0.21921415,  2.7589232 ],
       [-0.66016254, -1.25567643,  0.18593328, ..., -1.2461465 ,
         1.09959228, -1.11735376]], shape=(1500, 11))

In [16]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

knn = knn.fit(X_train,Y_train)

In [17]:
Y_pred = knn.predict(X_test)
Y_pred

array([0, 1, 0, ..., 1, 1, 0], shape=(1500,))

In [18]:
from sklearn.metrics import accuracy_score

print(accuracy_score(Y_pred,Y_test))

0.9106666666666666


In [19]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test,Y_pred)
cm

array([[382,  67],
       [ 67, 984]])