In [52]:
import numpy
import pandas

In [53]:
# Dataframe creation
data = pandas.read_csv('heart (1).csv')
df = pandas.DataFrame(data)
df

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [54]:
# Target  >>>  HeartDisease

In [55]:
# Unnecessory column removal
df = df.drop(columns= ['Age','Sex'],axis=1)
df

ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0             ATA        140          289          0     Normal    172   
1             NAP        160          180          0     Normal    156   
2             ATA        130          283          0         ST     98   
3             ASY        138          214          0     Normal    108   
4             NAP        150          195          0     Normal    122   
..            ...        ...          ...        ...        ...    ...   
913            TA        110          264          0     Normal    132   
914           ASY        144          193          1     Normal    141   
915           ASY        130          131          0     Normal    115   
916           ATA        130          236          0        LVH    174   
917           NAP        138          175          0     Normal    173   

    ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0                N      0.0       Up             0  
1                N      1.0     Flat             1  
2                N      0.0       Up             0  
3                Y      1.5     Flat             1  
4                N      0.0       Up             0  
..             ...      ...      ...           ...  
913              N      1.2     Flat             1  
914              N      3.4     Flat             1  
915              Y      1.2     Flat             1  
916              N      0.0     Flat             1  
917              N      0.0       Up             0  

[918 rows x 10 columns]

In [56]:
# Checking missing values
df.isna().sum()

ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [57]:
# Encoding

# Class = Label Encoder

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['ChestPainType'] = le.fit_transform(df['ChestPainType'])
df['RestingECG'] = le.fit_transform(df['RestingECG'])
df['ExerciseAngina'] = le.fit_transform(df['ExerciseAngina'])
df['ST_Slope'] = le.fit_transform(df['ST_Slope'])
df

ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  MaxHR  \
0                1        140          289          0           1    172   
1                2        160          180          0           1    156   
2                1        130          283          0           2     98   
3                0        138          214          0           1    108   
4                2        150          195          0           1    122   
..             ...        ...          ...        ...         ...    ...   
913              3        110          264          0           1    132   
914              0        144          193          1           1    141   
915              0        130          131          0           1    115   
916              1        130          236          0           0    174   
917              2        138          175          0           1    173   

     ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0                 0      0.0         2             0  
1                 0      1.0         1             1  
2                 0      0.0         2             0  
3                 1      1.5         1             1  
4                 0      0.0         2             0  
..              ...      ...       ...           ...  
913               0      1.2         1             1  
914               0      3.4         1             1  
915               1      1.2         1             1  
916               0      0.0         1             1  
917               0      0.0         2             0  

[918 rows x 10 columns]

In [58]:
X = df.iloc[:,:-1]
X
Y = df.iloc[:,-1]
Y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

Data preprocessing steps
=====================================
Handling Missing Values
Data Transform
Outliers
Scaling
Data Reduction

In [59]:
# Splitting
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)

X_train

ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  MaxHR  \
294              3         95            0          1           1    127   
36               0        140          306          1           1     87   
602              2        120          337          0           1     98   
715              2        108          141          0           1    175   
861              0        110          248          0           0    158   
..             ...        ...          ...        ...         ...    ...   
26               0        124          260          0           2    112   
430              0        128            0          1           2    148   
463              0        128            0          0           1    107   
566              0        150          171          0           1    128   
802              0        108          233          1           1    147   

     ExerciseAngina  Oldpeak  ST_Slope  
294               0      0.7         2  
36                1      1.5         1  
602               1      0.0         1  
715               0      0.6         1  
861               0      0.6         2  
..              ...      ...       ...  
26                1      3.0         1  
430               1      1.0         1  
463               0      0.0         2  
566               1      1.5         1  
802               0      0.1         2  

[642 rows x 9 columns]

In [60]:
# Scaling
from sklearn.preprocessing import StandardScaler    # Z = (x - mean) / Standard_Deviation

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)     # 70 %      fit takes mean,std of 70% data

X_test = scaler.transform(X_test)   # 30 %%!    X_test is transformed using mean,std,etc.. of the 70 % data
                                               #Hence model does not see the 30 % data
X_train
X_test

array([[ 0.24408885, -0.02543174,  1.29593339, ..., -0.82767105,
         0.27098817,  1.092019  ],
       [ 0.24408885, -0.689588  ,  0.04467177, ..., -0.82767105,
        -0.83948676,  1.092019  ],
       [ 2.34751224,  1.5242662 ,  0.31668517, ..., -0.82767105,
        -0.74694718, -0.569299  ],
       ...,
       [ 1.29580054,  0.52803181,  0.65216836, ..., -0.82767105,
        -0.56186803,  1.092019  ],
       [ 0.24408885,  0.97080265, -0.11853626, ..., -0.82767105,
        -0.83948676,  1.092019  ],
       [-0.80762284, -2.9034422 , -1.80501931, ...,  1.20820947,
         1.01130479, -2.230617  ]], shape=(276, 9))

In [61]:
# Algorithm
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

In [62]:
# Model Creation
model = knn.fit(X_train,Y_train)


In [63]:
# Testing
y_pred = model.predict(X_test)
y_pred

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1])

In [64]:
from sklearn.metrics import accuracy_score

print(accuracy_score(Y_test,y_pred))

0.8442028985507246


In [65]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test,y_pred)
cm

array([[110,  19],
       [ 24, 123]])