In [83]:
import numpy
import pandas

In [84]:
data = pandas.read_csv("health_lifestyle_dataset.csv")
df = pandas.DataFrame(data)
df

id  age  gender   bmi  daily_steps  sleep_hours  water_intake_l  \
0           1   56    Male  20.5         4198          3.9             3.4   
1           2   69  Female  33.3        14359          9.0             4.7   
2           3   46    Male  31.6         1817          6.6             4.2   
3           4   32  Female  38.2        15772          3.6             2.0   
4           5   60  Female  33.6         6037          3.8             4.0   
...       ...  ...     ...   ...          ...          ...             ...   
99995   99996   53    Male  33.1         4726          3.9             2.0   
99996   99997   22    Male  35.1        11554          4.5             3.1   
99997   99998   37    Male  18.9         3924          3.8             1.0   
99998   99999   72  Female  27.8        16110          5.6             0.8   
99999  100000   37    Male  35.4         8222          9.1             1.8   

       calories_consumed  smoker  alcohol  resting_hr  systolic_bp  \
0                   1602       0        0          97          161   
1                   2346       0        1          68          116   
2                   1643       0        1          90          123   
3                   2460       0        0          71          165   
4                   3756       0        1          98          139   
...                  ...     ...      ...         ...          ...   
99995               3118       0        1          56          105   
99996               1967       0        0          51          149   
99997               2328       0        0          69           92   
99998               3093       0        0          93          164   
99999               3942       0        1          71          145   

       diastolic_bp  cholesterol  family_history  disease_risk  
0               111          240               0             0  
1                65          207               0             0  
2                99          296               0             0  
3                95          175               0             0  
4                61          294               0             0  
...             ...          ...             ...           ...  
99995            76          282               0             0  
99996            77          192               0             0  
99997           117          218               0             0  
99998            72          188               0             0  
99999            80          276               0             1  

[100000 rows x 16 columns]

In [85]:
"""
# Display age, bmi, gender of people having age > 40
df.loc[df['age'] > 40, ['age','bmi','gender']]

# Display age, bmi, daily_steps of people having smoker = 1 
df.loc[df['smoker'] == 1, ['age','bmi','daily_steps']]

# Display age, gender, cholestrol of people having age above 40 and bmi above 30
df.loc[(df['age'] > 40) & (df['bmi'] > 30),['age','gender','cholesterol']]

# Dsisplay cholesterol, bmi, sleep_hours of people smoker = 0 or alcohol = 1
df.loc[(df['smoker'] == 0) | (df['alcohol'] == 1),['cholesterol','bmi','sleep_hours']]
"""

"\n# Display age, bmi, gender of people having age > 40\ndf.loc[df['age'] > 40, ['age','bmi','gender']]\n\n# Display age, bmi, daily_steps of people having smoker = 1 \ndf.loc[df['smoker'] == 1, ['age','bmi','daily_steps']]\n\n# Display age, gender, cholestrol of people having age above 40 and bmi above 30\ndf.loc[(df['age'] > 40) & (df['bmi'] > 30),['age','gender','cholesterol']]\n\n# Dsisplay cholesterol, bmi, sleep_hours of people smoker = 0 or alcohol = 1\ndf.loc[(df['smoker'] == 0) | (df['alcohol'] == 1),['cholesterol','bmi','sleep_hours']]\n"

In [86]:
"""
Different types of handling missing values in pandas
==========================================================

Deletion Methods (Removing missing values)
====================
"""
df.dropna() # Remove all rows with any missing values

"""
Imputation Methods (Filling missing values)
================================================
Used when data loss hurts the analysis

Replace missing values with meaningful substitutes

(mean, median, mode)
"""

'\nImputation Methods (Filling missing values)\n================================================\nUsed when data loss hurts the analysis\n\nReplace missing values with meaningful substitutes\n\n(mean, median, mode)\n'

In [87]:
df

id  age  gender   bmi  daily_steps  sleep_hours  water_intake_l  \
0           1   56    Male  20.5         4198          3.9             3.4   
1           2   69  Female  33.3        14359          9.0             4.7   
2           3   46    Male  31.6         1817          6.6             4.2   
3           4   32  Female  38.2        15772          3.6             2.0   
4           5   60  Female  33.6         6037          3.8             4.0   
...       ...  ...     ...   ...          ...          ...             ...   
99995   99996   53    Male  33.1         4726          3.9             2.0   
99996   99997   22    Male  35.1        11554          4.5             3.1   
99997   99998   37    Male  18.9         3924          3.8             1.0   
99998   99999   72  Female  27.8        16110          5.6             0.8   
99999  100000   37    Male  35.4         8222          9.1             1.8   

       calories_consumed  smoker  alcohol  resting_hr  systolic_bp  \
0                   1602       0        0          97          161   
1                   2346       0        1          68          116   
2                   1643       0        1          90          123   
3                   2460       0        0          71          165   
4                   3756       0        1          98          139   
...                  ...     ...      ...         ...          ...   
99995               3118       0        1          56          105   
99996               1967       0        0          51          149   
99997               2328       0        0          69           92   
99998               3093       0        0          93          164   
99999               3942       0        1          71          145   

       diastolic_bp  cholesterol  family_history  disease_risk  
0               111          240               0             0  
1                65          207               0             0  
2                99          296               0             0  
3                95          175               0             0  
4                61          294               0             0  
...             ...          ...             ...           ...  
99995            76          282               0             0  
99996            77          192               0             0  
99997           117          218               0             0  
99998            72          188               0             0  
99999            80          276               0             1  

[100000 rows x 16 columns]

In [88]:
df.isna().sum()

id                   0
age                  0
gender               0
bmi                  0
daily_steps          0
sleep_hours          0
water_intake_l       0
calories_consumed    0
smoker               0
alcohol              0
resting_hr           0
systolic_bp          0
diastolic_bp         0
cholesterol          0
family_history       0
disease_risk         0
dtype: int64

In [89]:
X = df.iloc[:,3:-1]
X
Y = df.iloc[:,-1]
Y

0        0
1        0
2        0
3        0
4        0
        ..
99995    0
99996    0
99997    0
99998    0
99999    1
Name: disease_risk, Length: 100000, dtype: int64

In [99]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)

X_train
X_test
Y_train
Y_test

12104    0
37035    0
68571    0
54322    0
15261    0
        ..
42580    0
89045    0
40077    0
83145    1
17995    1
Name: disease_risk, Length: 30000, dtype: int64

In [91]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_train

X_test = scaler.transform(X_test)
X_test


array([[-0.3351643 ,  1.57924285, -1.68017434, ..., -0.20028239,
         0.96485161, -0.65438648],
       [-1.24853253, -1.60363171,  1.62919037, ...,  1.64361259,
         0.20379849, -0.65438648],
       [-0.47689385, -0.50823157,  1.33282935, ...,  0.83690854,
        -0.3727569 , -0.65438648],
       ...,
       [-0.80759614, -1.46094359, -0.29715625, ..., -0.08503895,
         1.58753142,  1.52814894],
       [-1.51624391,  1.21678221, -0.05018874, ...,  0.03020448,
        -0.55725462,  1.52814894],
       [-0.76035296, -1.52508946, -1.43320683, ..., -1.06460816,
         1.33384705, -0.65438648]], shape=(30000, 12))

In [92]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

knn = knn.fit(X_train,Y_train)

In [93]:
y_pred = knn.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(30000,))

In [94]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_pred,Y_test))

0.7023333333333334


In [95]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_pred,Y_test)
cm

array([[20298,  6637],
       [ 2293,   772]])