In [13]:
import numpy
import pandas

In [14]:
data = pandas.read_csv("earthquake_alert_balanced_dataset.csv")
df = pandas.DataFrame(data)
df

,magnitude,depth,cdi,mmi,sig,alert
0,7.00,14.0,8.0,7.0,0.0,green
1,6.90,25.0,4.0,4.0,-33.0,green
2,7.00,579.0,3.0,3.0,-13.0,green
3,7.30,37.0,5.0,5.0,65.0,green
4,6.60,624.0,0.0,2.0,-98.0,green
...,...,...,...,...,...,...
1295,6.87,11.0,9.0,7.0,13.0,yellow
1296,7.85,93.0,8.0,6.0,-51.0,yellow
1297,7.48,142.0,7.0,6.0,120.0,yellow
1298,7.04,51.0,7.0,6.0,-115.0,yellow


In [15]:
# target >>> alert

In [16]:
df.isna().sum()

magnitude    0
depth        0
cdi          0
mmi          0
sig          0
alert        0
dtype: int64

In [17]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['alert'] = le.fit_transform(df['alert'])
df

,magnitude,depth,cdi,mmi,sig,alert
0,7.00,14.0,8.0,7.0,0.0,0
1,6.90,25.0,4.0,4.0,-33.0,0
2,7.00,579.0,3.0,3.0,-13.0,0
3,7.30,37.0,5.0,5.0,65.0,0
4,6.60,624.0,0.0,2.0,-98.0,0
...,...,...,...,...,...,...
1295,6.87,11.0,9.0,7.0,13.0,3
1296,7.85,93.0,8.0,6.0,-51.0,3
1297,7.48,142.0,7.0,6.0,120.0,3
1298,7.04,51.0,7.0,6.0,-115.0,3


In [18]:
X = df.iloc[:,:-1]
X
Y = df.iloc[:,-1]
Y

0       0
1       0
2       0
3       0
4       0
       ..
1295    3
1296    3
1297    3
1298    3
1299    3
Name: alert, Length: 1300, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)
X_train

,magnitude,depth,cdi,mmi,sig
1061,6.58,13.0,6.0,7.0,-46.0
610,8.17,23.0,9.0,8.0,-88.0
824,7.49,19.0,8.0,8.0,-22.0
420,6.98,23.0,8.0,7.0,-9.0
897,7.40,9.0,8.0,9.0,15.0
...,...,...,...,...,...
77,6.70,10.0,8.0,8.0,8.0
863,7.02,19.0,8.0,8.0,-54.0
1077,7.17,16.0,8.0,8.0,24.0
1182,7.09,142.0,5.0,6.0,-2.0


In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_train

X_test = scaler.transform(X_test)

X_test

array([[-0.44789321, -0.3327934 , -0.01159159,  0.02143202, -0.05056053],
       [-0.42429805,  0.43484062, -0.01159159, -0.72868869, -1.32637531],
       [-0.37710773,  0.62156241, -0.47021521,  0.02143202,  0.93456228],
       ...,
       [ 0.44872293, -0.28092624,  0.44703204,  0.02143202,  0.67616941],
       [-0.84901096,  5.2481134 , -1.84608609, -2.97905083, -1.00338422],
       [-0.37710773, -0.38466056, -0.92883884, -0.72868869, -0.19590651]],
      shape=(390, 5))

In [21]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

model = knn.fit(X_train,Y_train)

In [22]:
Y_pred = model.predict(X_test)
Y_pred

array([1, 3, 3, 1, 3, 3, 0, 0, 2, 1, 1, 2, 2, 0, 1, 0, 1, 0, 2, 2, 1, 2,
       2, 0, 2, 2, 1, 3, 2, 3, 1, 1, 1, 2, 2, 3, 2, 2, 0, 2, 0, 2, 3, 3,
       0, 3, 1, 0, 1, 2, 1, 0, 2, 0, 1, 0, 1, 2, 1, 1, 1, 0, 3, 3, 1, 1,
       1, 0, 0, 2, 0, 3, 2, 0, 2, 2, 2, 2, 0, 3, 2, 2, 2, 0, 1, 1, 1, 2,
       3, 3, 0, 2, 2, 1, 1, 1, 3, 2, 1, 2, 2, 0, 2, 1, 3, 3, 1, 1, 2, 0,
       2, 2, 2, 1, 3, 3, 2, 1, 2, 0, 2, 0, 3, 3, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 2, 2, 1, 3, 2, 1, 3, 1, 3, 0, 2, 2, 2, 0, 1, 3, 1, 1, 1, 2, 0,
       3, 1, 0, 1, 2, 1, 3, 0, 2, 3, 2, 0, 0, 3, 1, 3, 1, 0, 2, 2, 1, 3,
       2, 1, 0, 1, 0, 1, 1, 3, 0, 3, 0, 0, 3, 2, 3, 1, 3, 2, 3, 3, 3, 1,
       0, 1, 3, 1, 1, 1, 3, 2, 3, 0, 1, 2, 1, 2, 3, 1, 2, 0, 3, 0, 2, 0,
       3, 3, 1, 3, 0, 0, 2, 2, 2, 3, 1, 2, 2, 3, 0, 3, 2, 2, 0, 1, 0, 0,
       1, 1, 0, 1, 3, 2, 2, 0, 2, 0, 1, 1, 3, 1, 1, 3, 2, 2, 0, 2, 3, 0,
       0, 1, 2, 3, 0, 1, 3, 2, 1, 0, 0, 0, 2, 1, 1, 3, 3, 1, 2, 3, 2, 2,
       3, 3, 1, 2, 2, 0, 0, 2, 3, 2, 2, 0, 2, 1, 0,

In [23]:
from sklearn.metrics import accuracy_score

print(accuracy_score(Y_test,Y_pred))


0.8589743589743589


In [24]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test,Y_pred)
cm

array([[82,  5,  3, 11],
       [ 2, 93, 10,  2],
       [ 0,  2, 92,  0],
       [ 7,  8,  5, 68]])