In [59]:
import numpy
import pandas

In [60]:
data = pandas.read_csv("earthquake_alert_balanced_dataset.csv")
df = pandas.DataFrame(data)
df

magnitude  depth  cdi  mmi    sig   alert
0          7.00   14.0  8.0  7.0    0.0   green
1          6.90   25.0  4.0  4.0  -33.0   green
2          7.00  579.0  3.0  3.0  -13.0   green
3          7.30   37.0  5.0  5.0   65.0   green
4          6.60  624.0  0.0  2.0  -98.0   green
...         ...    ...  ...  ...    ...     ...
1295       6.87   11.0  9.0  7.0   13.0  yellow
1296       7.85   93.0  8.0  6.0  -51.0  yellow
1297       7.48  142.0  7.0  6.0  120.0  yellow
1298       7.04   51.0  7.0  6.0 -115.0  yellow
1299       6.50    9.0  9.0  8.0  -29.0  yellow

[1300 rows x 6 columns]

In [61]:
# target >>> alert

In [62]:
df.isna().sum()

magnitude    0
depth        0
cdi          0
mmi          0
sig          0
alert        0
dtype: int64

In [63]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['alert'] = le.fit_transform(df['alert'])
df

magnitude  depth  cdi  mmi    sig  alert
0          7.00   14.0  8.0  7.0    0.0      0
1          6.90   25.0  4.0  4.0  -33.0      0
2          7.00  579.0  3.0  3.0  -13.0      0
3          7.30   37.0  5.0  5.0   65.0      0
4          6.60  624.0  0.0  2.0  -98.0      0
...         ...    ...  ...  ...    ...    ...
1295       6.87   11.0  9.0  7.0   13.0      3
1296       7.85   93.0  8.0  6.0  -51.0      3
1297       7.48  142.0  7.0  6.0  120.0      3
1298       7.04   51.0  7.0  6.0 -115.0      3
1299       6.50    9.0  9.0  8.0  -29.0      3

[1300 rows x 6 columns]

In [64]:
X = df.iloc[:,:-1]
X
Y = df.iloc[:,-1]
Y

0       0
1       0
2       0
3       0
4       0
       ..
1295    3
1296    3
1297    3
1298    3
1299    3
Name: alert, Length: 1300, dtype: int64

In [65]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)
X_train

magnitude  depth  cdi  mmi    sig
573        6.91   51.0  8.0  7.0   55.0
36         7.30  165.0  8.0  7.0 -103.0
287        6.70   12.0  4.0  5.0  -77.0
474        6.57   11.0  8.0  7.0   11.0
821        7.21    9.0  9.0  8.0   94.0
...         ...    ...  ...  ...    ...
163        7.30  146.0  8.0  6.0   34.0
1179       7.91   23.0  8.0  8.0   41.0
301        6.60   10.0  8.0  7.0  -35.0
179        7.50   19.0  8.0  5.0   87.0
711        7.28   18.0  8.0  7.0   32.0

[910 rows x 5 columns]

In [66]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_train

X_test = scaler.transform(X_test)

X_test

array([[-0.16738945,  0.16153441, -1.73262362,  0.04351783, -0.05649494],
       [-0.39846409, -0.24428668, -1.29306758, -2.24116819, -0.37660945],
       [-0.3291417 , -0.02652902,  0.46515655,  0.04351783,  1.06390587],
       ...,
       [-1.32276264, -0.25418475, -3.05129171, -2.24116819, -1.73709614],
       [ 0.06368519, -0.28387898,  0.90471258, -0.71804418,  0.34364821],
       [-0.81439844, -0.37296166,  0.02560052,  0.04351783, -0.92080413]],
      shape=(390, 5))

In [67]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

model = knn.fit(X_train,Y_train)

In [68]:
Y_pred = model.predict(X_test)
Y_pred

array([3, 0, 1, 2, 2, 0, 3, 3, 0, 0, 3, 0, 2, 2, 0, 3, 0, 1, 0, 3, 1, 3,
       1, 0, 3, 3, 0, 2, 1, 3, 1, 1, 0, 1, 2, 1, 3, 2, 1, 3, 1, 3, 1, 1,
       1, 3, 2, 3, 0, 1, 2, 0, 3, 2, 3, 1, 1, 3, 3, 2, 1, 0, 2, 2, 1, 2,
       2, 1, 2, 3, 0, 1, 2, 0, 1, 0, 1, 3, 3, 1, 3, 2, 1, 0, 3, 0, 3, 3,
       2, 1, 1, 1, 3, 0, 0, 2, 1, 1, 1, 3, 3, 3, 1, 3, 2, 2, 3, 1, 2, 1,
       0, 0, 0, 2, 3, 2, 1, 3, 2, 0, 0, 0, 2, 2, 0, 3, 2, 1, 1, 0, 2, 0,
       3, 1, 1, 2, 0, 3, 1, 3, 0, 2, 3, 3, 3, 3, 1, 1, 2, 1, 1, 1, 1, 0,
       1, 1, 2, 2, 1, 2, 3, 2, 2, 3, 2, 0, 3, 2, 3, 1, 2, 0, 3, 1, 2, 2,
       1, 1, 1, 1, 3, 0, 2, 3, 3, 3, 1, 1, 1, 2, 0, 2, 2, 2, 1, 0, 1, 1,
       0, 3, 2, 0, 1, 3, 1, 2, 3, 2, 2, 3, 2, 3, 2, 0, 3, 0, 0, 2, 3, 1,
       2, 3, 1, 2, 3, 2, 1, 2, 3, 1, 1, 0, 1, 1, 1, 2, 2, 2, 2, 3, 2, 2,
       0, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2, 0, 0, 2, 1,
       3, 3, 3, 2, 1, 2, 0, 0, 1, 0, 2, 2, 3, 3, 0, 3, 1, 0, 3, 2, 0, 0,
       2, 2, 3, 3, 2, 1, 0, 0, 2, 0, 1, 3, 3, 0, 2,

In [69]:
from sklearn.metrics import accuracy_score

print(accuracy_score(Y_test,Y_pred))


0.8435897435897436


In [70]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test,Y_pred)
cm

array([[73,  0,  3, 16],
       [ 2, 86,  7,  5],
       [ 0, 10, 96,  0],
       [ 4, 12,  2, 74]])