In [79]:
import numpy
import pandas

In [80]:
data = pandas.read_csv('weather_classification_data.csv')
df = pandas.DataFrame(data)
df

Temperature  Humidity  Wind Speed  Precipitation (%)    Cloud Cover  \
0             14.0        73         9.5               82.0  partly cloudy   
1             39.0        96         8.5               71.0  partly cloudy   
2             30.0        64         7.0               16.0          clear   
3             38.0        83         1.5               82.0          clear   
4             27.0        74        17.0               66.0       overcast   
...            ...       ...         ...                ...            ...   
13195         10.0        74        14.5               71.0       overcast   
13196         -1.0        76         3.5               23.0         cloudy   
13197         30.0        77         5.5               28.0       overcast   
13198          3.0        76        10.0               94.0       overcast   
13199         -5.0        38         0.0               92.0       overcast   

       Atmospheric Pressure  UV Index  Season  Visibility (km)  Location  \
0                   1010.82         2  Winter              3.5    inland   
1                   1011.43         7  Spring             10.0    inland   
2                   1018.72         5  Spring              5.5  mountain   
3                   1026.25         7  Spring              1.0   coastal   
4                    990.67         1  Winter              2.5  mountain   
...                     ...       ...     ...              ...       ...   
13195               1003.15         1  Summer              1.0  mountain   
13196               1067.23         1  Winter              6.0   coastal   
13197               1012.69         3  Autumn              9.0   coastal   
13198                984.27         0  Winter              2.0    inland   
13199               1015.37         5  Autumn             10.0  mountain   

      Weather Type  
0            Rainy  
1           Cloudy  
2            Sunny  
3            Sunny  
4            Rainy  
...            ...  
13195        Rainy  
13196        Snowy  
13197       Cloudy  
13198        Snowy  
13199        Rainy  

[13200 rows x 11 columns]

In [81]:
df.dtypes

Temperature             float64
Humidity                  int64
Wind Speed              float64
Precipitation (%)       float64
Cloud Cover              object
Atmospheric Pressure    float64
UV Index                  int64
Season                   object
Visibility (km)         float64
Location                 object
Weather Type             object
dtype: object

In [82]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for i in df.columns:

    if df[i].dtype == 'object':

        df[i] = le.fit_transform(df[i])



In [83]:
df

Temperature  Humidity  Wind Speed  Precipitation (%)  Cloud Cover  \
0             14.0        73         9.5               82.0            3   
1             39.0        96         8.5               71.0            3   
2             30.0        64         7.0               16.0            0   
3             38.0        83         1.5               82.0            0   
4             27.0        74        17.0               66.0            2   
...            ...       ...         ...                ...          ...   
13195         10.0        74        14.5               71.0            2   
13196         -1.0        76         3.5               23.0            1   
13197         30.0        77         5.5               28.0            2   
13198          3.0        76        10.0               94.0            2   
13199         -5.0        38         0.0               92.0            2   

       Atmospheric Pressure  UV Index  Season  Visibility (km)  Location  \
0                   1010.82         2       3              3.5         1   
1                   1011.43         7       1             10.0         1   
2                   1018.72         5       1              5.5         2   
3                   1026.25         7       1              1.0         0   
4                    990.67         1       3              2.5         2   
...                     ...       ...     ...              ...       ...   
13195               1003.15         1       2              1.0         2   
13196               1067.23         1       3              6.0         0   
13197               1012.69         3       0              9.0         0   
13198                984.27         0       3              2.0         1   
13199               1015.37         5       0             10.0         2   

       Weather Type  
0                 1  
1                 0  
2                 3  
3                 3  
4                 1  
...             ...  
13195             1  
13196             2  
13197             0  
13198             2  
13199             1  

[13200 rows x 11 columns]

In [84]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [85]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)

In [86]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)

X_test = sc.transform(X_test)

In [87]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

model = rf.fit(X_train,Y_train)

Y_pred = model.predict(X_test)

In [88]:
from sklearn.metrics import accuracy_score,confusion_matrix

print(accuracy_score(Y_test,Y_pred))

print(confusion_matrix(Y_test,Y_pred))

0.9156565656565656
[[900  57  16  25]
 [ 44 886  18  20]
 [ 25  18 935  25]
 [ 48  27  11 905]]
