In [53]:
import numpy
import pandas

In [54]:
data = pandas.read_csv('Telecust1.csv')
df = pandas.DataFrame(data)
df

region  tenure  age  income  ...  retire  gender  reside  custcat
0         2      13   44      64  ...       0       0       2        A
1         3      11   33     136  ...       0       0       6        D
2         3      68   52     116  ...       0       1       2        C
3         2      33   33      33  ...       0       1       1        A
4         2      23   30      30  ...       0       0       4        C
..      ...     ...  ...     ...  ...     ...     ...     ...      ...
995       3      10   39      27  ...       0       1       3        A
996       1       7   34      22  ...       0       1       1        A
997       3      67   59     944  ...       0       1       1        D
998       3      70   49      87  ...       0       1       1        C
999       3      50   36      39  ...       0       1       3        B

[1000 rows x 12 columns]

In [55]:
df.isna().sum()

region     0
tenure     0
age        0
income     0
marital    0
address    0
ed         0
employ     0
retire     0
gender     0
reside     0
custcat    0
dtype: int64

In [56]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['custcat'] = le.fit_transform(df['custcat'])

In [57]:
df

region  tenure  age  income  ...  retire  gender  reside  custcat
0         2      13   44      64  ...       0       0       2        0
1         3      11   33     136  ...       0       0       6        3
2         3      68   52     116  ...       0       1       2        2
3         2      33   33      33  ...       0       1       1        0
4         2      23   30      30  ...       0       0       4        2
..      ...     ...  ...     ...  ...     ...     ...     ...      ...
995       3      10   39      27  ...       0       1       3        0
996       1       7   34      22  ...       0       1       1        0
997       3      67   59     944  ...       0       1       1        3
998       3      70   49      87  ...       0       1       1        2
999       3      50   36      39  ...       0       1       3        1

[1000 rows x 12 columns]

In [58]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [59]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

In [60]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [61]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()

model = dt.fit(X_train, Y_train)

Y_pred = model.predict(X_test)

In [62]:
from sklearn.metrics import accuracy_score,confusion_matrix

cm = confusion_matrix(Y_test, Y_pred)

print(cm)
print(accuracy_score(Y_test, Y_pred))

[[18 13 30 19]
 [ 9 19 19 16]
 [32 14 32  9]
 [19 14 13 24]]
0.31
